version: '2.23'
services:
  server:
    build: ./server
    container_name: backend-c 
    ports:
      - "8000:8000"

  client:
    build: ./client
    container_name: frontend-c
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true